name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Run Unit tests
      run: npm run test:unit
      
    - name: Display Username
      run: echo 'HeliXs66'

  run_ui_tests:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install
  
    - name: Install playwright browsers
      run: npx playwright install

    - name: Start application
      run: npm start &

    - name: Run UI tests
      run: npm run test:ui

  deploy-render:
    needs: run_ui_tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}